[package]
name = "ls_clone"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A clone of ls that i wrote in a weekend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
